### ISSUE TITLE
Display not showing proper on ONE device

### ISSUE THREAD

**Issue by KageKeeper** [gadgetchnnel/lovelace-home-feed-card#101]
I am having an interesting issue. I have the Home Feed card configured, and it is looking proper on my PC as well as my mobile phone. However, on the Samsung Tablet that I am creating the dashboard for, the Name of the entity does not show. Just the icon and the time since last event.

I have closed and refreshed the HA instance. To no avail. Very baffling.

Here is a snippet of my set up.

```
type: custom:home-feed-card
title: null
show_empty: false
scrollbars_enabled: false
max_item_count: 4
state_color: true
exact_durations: true
entities:
  - entity: binary_sensor.basement_motion_sensor_ias_zone
    icon: mdi:motion-sensor
    name: Basement Motion
```
