### ISSUE TITLE
Timer shows last updated and not finishes_at

### ISSUE THREAD

**Issue by theOrakle** [gadgetchnnel/lovelace-home-feed-card#102]

**Comment by theOrakle** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/37029980/229357958-81abd901-e7ab-431b-bfc3-9b0ebdfdbb28.png">

No matter what I try - I couldn't get it mapped.
```
- entity: timer.recycler
  content_template: '{{display_name}} done at {{finishes_at}}'
  exclude_states:
  - idle

```
