### ISSUE TITLE
Cannot filter on state using exclude_states  

### ISSUE THREAD

**Issue by kaosmagix** [gadgetchnnel/lovelace-home-feed-card#11]
I try to use your card to show lines for the garage collection sensors for today and tomorrow. These  uses the state None if nothing is collected the tomorrow. I cannot filter this state using the exclude_filter property. I tried different values, but I cannot get it to work. I checked the state output in Node-RED to make sure what the return value actually is. I have the same problem with only showing open doors/windows.

```
  - type: 'custom:home-feed-card'
    title: Home Feed
    show_empty: false
    more_info_on_tap: true
    entities:
    - entity: sensor.gad_vandaag
      exclude_states: 
        None
    - entity: sensor.gad_morgen
      exclude_states: 
        none
    - entity: binary_sensor.badkamer_ramen
      exclude_states: 
        Closed
    - entity: binary_sensor.slaapkamer_ramen
      exclude_states: 
        Closed
```

Any suggestions welcome. Thanks in advance.

**Comment by gadgetchnnel** [comment]
There are a couple of issues with your config.

1. exclude_states should be a list, so each item should start with **-**
2. The states should be the raw states, rather than the display state. Which for door and window sensors is "on" for open and "off" for closed (check the states in the states page under Developer Tools to see the actual states).

This would make your config like this:

```
- type: 'custom:home-feed-card'
    title: Home Feed
    show_empty: false
    more_info_on_tap: true
    entities:
    - entity: sensor.gad_vandaag
      exclude_states: 
        - None
    - entity: sensor.gad_morgen
      exclude_states: 
        - None
    - entity: binary_sensor.badkamer_ramen
      exclude_states: 
        - "off"
    - entity: binary_sensor.slaapkamer_ramen
      exclude_states: 
        - "off"
```
Note: You may need to check the exact states for those that return None, but using None is working for my sensors which do this.
