### ISSUE TITLE
[Feature Request] Addition of attribute_map configuration entry

### ISSUE THREAD

**Issue by twi252** [gadgetchnnel/lovelace-home-feed-card#111]
I have the following entity configuration:

```
  - entity: binary_sensor.0x00159c00091a7d89_contact
    attribute: contact
    content_template: '{{display_name}} contact state {{contact}}'
    remove_repeats: false
    include_history: true
    exclude_states:
      - unavailable
```

I use the 'attribute' contact, and i'd like to map the words false/true to open/closed. This is possible with state_map, but there does not seem to be an equivalent for attributes (attribute_map).

Thought i'd submit a feature-request for this.

Thanks.
