### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by pdwonline** [gadgetchnnel/lovelace-home-feed-card#116]
Would be nice to be able to hide entities based an expression or value of a sensor like this:

```
type: 'custom:home-feed-card'
  title: Home Feed
  show_empty: false
  entities:
     - entity: sensor.something
        multiple_items: false
        hidewhen: "{{states(sensor.something) | int(0) > 10}}"
```

**Comment by notabene00** [comment]
First thing first, author, great work. Hope you don’t mind if I place here a link to my fork.
https://github.com/notabene00/lovelace-home-feed-card

@pdwonline you can just add `notabene00/lovelace-home-feed-card` to HACS and install from there.

I've implemented `jinja2` templates support for `content_template`, added `condition`, `attribute` options and made `icon` templateable.

`condition`, if defined, must be a jinja template string, if it renders to 'True', element will be displayed, otherwise - no.
`attribute` parameter, if defined, must be an attribute name of the `entity` that is a `timestamp` or a `datetime` and then `attribute`s value will be used to calculate timediffs and display "state". can also be a template string.
`icon` just can contain jinja2-templates now to be in sync with any entity's state changes.

**Comment by Krakoukas73** [comment]
Hi @notabene00 ,

I've added your fork. Could you please show few examples for condition usage and jinja2 syntax in content_template ?
Thank you !

**Comment by notabene00** [comment]
@Krakoukas73 
> Could you please show few examples 

Sure. Here you go:
```yaml
entities:
  - entity: sensor.marinas_schedule
    icon: mdi:human-female-female-child
    condition: '{{ as_local(as_datetime(state_attr(entity, attribute))) > now() }}'
    attribute: "{ 'end_date' if state_attr(entity, 'is_working_now') else 'start_date' }}"
    content_template: >-
      Марина {{ 'заканчивает' if state_attr(entity, 'is_working_now') else
      'начинает' }} в {{ state_attr(entity, attribute).strftime('%H:%M') }}

```
Is something like this enough?
