### ISSUE TITLE
How does entity attribute work?

### ISSUE THREAD

**Issue by Cloud500** [gadgetchnnel/lovelace-home-feed-card#121]
I have an entity which contains a timestamp as the `End time` attribute.
If I read the documentation correctly, I can use the `attribute` parameter to display this as the status:

> Entity object -> attribute (optional, added in 0.6.0)
> Define an attribute to use instead of the state for the entity in the list

But basically, it doesn't matter what I write in attribute, it always shows `last change`...

Am I just too stupid or is this really a bug?
(I mean, I'm still quite new to the HA universe)

lovelace-home-feed-card version: 0.6.5

sensor attributes:
```
Message => str
All day => bool
Start time => timestamp
End time => timestamp
Description => str
```

card:
```
type: custom:home-feed-card
title: Current free Game
card_id: main_feed
show_empty: false
more_info_on_tap: true
state_color: true
compact_mode: true
entities:
  - entity: calendar.epic_games_store_rabatt_spiele
    content_template: "{{message}}"
    attribute: end_time
```
	
(I have tried various versions, `end_time`, `“end_time”`, `“End time”`, `End time`, `{{end_time}}`, and more, even `message` which works in `content_template` does not work in “attribute”.
However, if I enter `"{{end_time}}"` as `content_template`, the date is displayed.)

Any ideas?

PS:
I first tried it “normally” via `calenders`, but “last week” as status doesn't help me, because I want to know how much longer and not since when
