### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by rdehuyss** [gadgetchnnel/lovelace-home-feed-card#16]
Just wanted to chip in on the performance issue: I can also confirm it. With me, chrome is taking 77% and homeassistant 50% when using this card. I'm using the dev version installed with HACS.

What I notice is a whole lot of calls to `http://127.0.0.1:8123/api/history/period?filter_entity_id=` each 10 seconds although I only have two entities.

```
      - type: 'custom:home-feed-card'
        title: Home Feed
        show_empty: true
        more_info_on_tap: true
        entities:
          - entity: binary_sensor.voordeur
            exclude_states: 
              - "off" 
              - "unknown"
          - entity: binary_sensor.bureau_schuifraam_1
            exclude_states: 
              - "off" 
              - "unknown"
```

![Screenshot from 2019-09-05 09-39-25](https://user-images.githubusercontent.com/567842/64321577-19343380-cfc1-11e9-9103-29d7e1e44ebd.png)

Removing the above configuration from my lovelace and cpu usage is back normal.

**Edit 1**
Some more info: each time HomeAssistant sends an Update through set hass, the stack is as follows:
```
- set hass(hass)
- refreshEntityHistory
- getLiveEntityHistory *which makes http calls even if entity_ids is empty*
```

I cannot completely follow the logic/code of your card since HomeAssistant provides you with updates of everything by calling set hass(hass) => hass contains the latest state and instead of doing http calls each time, can't you store the changes yourself in local_storage? This would eliminate all the http calls and thus solve the performance issue I think.
Anyway: set hass(hass) can happen several times per second and since the history api is rather slow, I at least would throttle the calls to history/period.

Cheers!
