### ISSUE TITLE
"error handling" when listing entities that do not exist

### ISSUE THREAD

**Issue by lolouk44** [gadgetchnnel/lovelace-home-feed-card#25]
I have a list of entities I want to display in the feed, however if one of the entities listed does not exist, nothing is displayed at all.
Can this be improved so that the feed still displays, but maybe throw an alert on the card?

**Comment by gadgetchnnel** [comment]
@lolouk44 This should now be in the latest beta version (0.3.5b3).It will display the standard "Entity not available" message like the default Lovelace cards, like **entities**.

**Comment by lolouk44** [comment]
Thanks @gadgetchnnel. Will try and feed back

**Comment by lolouk44** [comment]
@gadgetchnnel Doesnt' seem to work?
Just added a "fake" entity to my list of entity ids and nothing gets displayed:
```
  - type: custom:home-feed-card
    title: Sensors Activity Feed
    show_empty: true
    more_info_on_tap: true
    max_item_count: 99
    entities:
        - binary_sensor.alert_aloe_vera_battery_too_low
        - binary_sensor.alert_aloe_vera_humidity_too_low
        - binary_sensor.alert_aloe_vera_humidity_too_low2 <-- fake entity_id
```
