### ISSUE TITLE
Display last x states of an entity

### ISSUE THREAD

**Issue by jannislehmann** [gadgetchnnel/lovelace-home-feed-card#26]
Hey,

is it possible to show all last states from one entity?
I have a door and I want to see when it was opened and when it was closed.
With the default configuration I only have the latest state per entity.

**Comment by gadgetchnnel** [comment]
You can use the [include_history](https://github.com/gadgetchnnel/lovelace-home-feed-card#include_history-optional-defaults-to-false) option for this, for example:

```YAML
type: 'custom:home-feed-card'
  title: Home Feed
  show_empty: false
  id_filter: ^home_feed_.*
  entities:
      - entity: binary_sensor.front_door
        name: Front Door
        include_history: true
        max_history: 5
```
By default repeated states are excluded, for example  if it goes from Open to Open without going to Closed (which could happen as unknown states are filtered out) but this can be disabled by using `remove_repeats: false`
