### ISSUE TITLE
How to extract items from list

### ISSUE THREAD

**Issue by dibyadip-das** [gadgetchnnel/lovelace-home-feed-card#35]
Here is a calendar config I want to add to my feed:

![image](https://user-images.githubusercontent.com/47345141/76158640-dd2f8600-613d-11ea-8b34-8548f57a6d16.png)

Now while configuring I am unable to fetch the items under all_tasks:
![image](https://user-images.githubusercontent.com/47345141/76158648-0cde8e00-613e-11ea-88fd-f23398b6788f.png)

Can you please help me resolve this issue?

**Comment by gadgetchnnel** [comment]
I have just released a new beta version (0.4.1b1) which should allow this to work (previously it would only work if the attribute referred to by **list_attribute** contained a list of objects, rather than strings. The new version allows this by treating them as as objects like {value:"string value"} and so can be referred to in content_template as {{value}}, for example:

```
type: 'custom:home-feed-card'
title: Home Feed
show_empty: false
entities:
  - entity: calendar.alexa_shopping_list
    multiple_items: true
    list_attribute: all_tasks
    content_template: '{{value}}'
    icon: 'mdi:shopping'
```
