### ISSUE TITLE
Help with entity history  not showing

### ISSUE THREAD

**Issue by rrroonn** [gadgetchnnel/lovelace-home-feed-card#36]
Hi,

I would like to have the Home Feed show the last 'n' state changes of an entity.  At this stage I have dummy'd something up.  I have a sensor that follows an MQTT topic and thus changes by publishing to that topic.  I am attempting to get the Home Feed to show the last (say) 5 of those.

this is the code I have in the "raw" config:
```
type: 'custom:home-feed-card'
title: History not working
id_filter: "^home_feed_.*"
show_empty: false
entities:
  - entity: sensor.wip_test
    include_history: false
  - entity: sensor.wip_test
    include_history: true
    max_history: 5
```
You can see that I have added the same information twice, once as a single entity, once with history enabled.

Here is what it looks like in lovelace:

![h1](https://user-images.githubusercontent.com/20292325/76372086-0e9b9200-6388-11ea-80d3-a0373b49f9e1.jpg)

Here is what the history looks like:

![h2](https://user-images.githubusercontent.com/20292325/76371937-a51b8380-6387-11ea-83c9-cfbe2f88ba94.jpg)

I have tried other sensor types and run into similar issues - though sometimes different.  In once case, it would only show old entries and nothing from today.

Am I doing something wrong?  Assistance appreciated.

Note:  I downloaded the latest non-dev release and installed for first time today.

thanks,

Ron

**Comment by rrroonn** [comment]
Ok, figured out that location of files makes a difference.   I had moved them up one dir level as I trouble getting the custom card to be recognised.  Moved it back to specified location and history is working, though not without problems:

The history is continually jumping and refreshing despite no changes to the sensor ... any ideas?

thanks,

Ron

**Comment by rrroonn** [comment]
Ok, I am no longer sure what is going on because I opened up Home Assistant using Microsoft Edge:
![h3](https://user-images.githubusercontent.com/20292325/76373605-a00d0300-638c-11ea-9b77-91910c3be4b2.jpg)

I closed down chrome and rebooted the HA docker volume but chrome still looks like this:
![h4](https://user-images.githubusercontent.com/20292325/76373786-1a3d8780-638d-11ea-8104-f674ea05a011.jpg)

but jumping all over the place

This is my lovelace config

![h5](https://user-images.githubusercontent.com/20292325/76373812-304b4800-638d-11ea-90b5-2d9035eec80b.jpg)

This is my file system

![h7](https://user-images.githubusercontent.com/20292325/76373823-37725600-638d-11ea-8953-8f56affee364.jpg)

 The android HA app has the same jumpiness about it to.  Its like the history content keeps refreshing and redrawing

This was caught in the process of jumping/updating:

![h9](https://user-images.githubusercontent.com/20292325/76374486-17439680-638f-11ea-9379-3ae57c4a10ba.jpg)

**Comment by gadgetchnnel** [comment]
I've never tested it with the same entity twice, with and without history and I think that would be likely to cause issues. If you still have it like that, have you tried with just the version with history?

Otherwise, can you try with the latest version, 0.4.0, to see if that changes anything.

**Comment by rrroonn** [comment]
Thanks,

Tried 4.0 and same problem.

Tried just one entity and same problem - still jumping around.  It looks like it is constant refreshing / redrawing.

**Comment by gadgetchnnel** [comment]
I don't know about the jumping around, but missing updated be be due to one of two things:
* By default it skips repeated states in the history (e.g. if it is updated to the same state twice in succession. You can set **remove_repeats** to false to prevent this
* By default, only the history for the last day is taken into account, you can use the new **history_days_back** option (added in 0.4.0) to change this.

With both of those options it would look something like:

```
type: 'custom:home-feed-card'
title: History not working
id_filter: "^home_feed_.*"
show_empty: false
entities:
  - entity: sensor.wip_test
    include_history: true
    max_history: 5
    remove_repeats: false
    history_days_back: 7
```
