### ISSUE TITLE
content_template doesnt seem to render {{state}}

### ISSUE THREAD

**Issue by jaburges** [gadgetchnnel/lovelace-home-feed-card#41]
Hi there,
so i'm using `content_template` as per below. Note MQTT devices do not have a `friendly_name` so using `name:` in the card config.
```yaml
- type: 'custom:home-feed-card'
  title: Home Feed
  compact_mode: on
  scrollbars_enabled: false
  max_item_count: 5
  entities:
    - entity: binary_sensor.living_room_motion_sensor
      name: Living Room 
      content_template: '{{state}} in the {{display_name}}'
      state_map:
        on: "Motion"
      exclude_states:
        - "off"
```
With the above I just get `in the` displayed, no state information.
I have tried using customize.yaml in my configuration to add a `friendly_name` to these devices, but that doesnt work either.
If I comment out `content_template` I get `Living Room @ Detected` as expected.

I very easily could be missing something, just doesnt seem to be rendering the templates.
