### ISSUE TITLE
Not extracting attribute values

### ISSUE THREAD

**Issue by Gamelauncher** [gadgetchnnel/lovelace-home-feed-card#55]
I have a sensor with some attributes but whatever I do, I don't get the correct values displayed.

![Screen Shot 2020-10-31 at 12 16 55](https://user-images.githubusercontent.com/6050522/97776755-93375c80-1b73-11eb-84a4-6f85150ba48f.png)

```
      - id: alarm_events_feed
        type: "custom:home-feed-card"
        title: Events
        show_header_toggle: false
        compact_mode: true
        entities:
          - entity: sensor.event_c2be08
            name: Events
            content_template: '{{ state }}'
            include_history: true
            max_history: 5
            remove_repeats: false
```

I've tried setting to the content_template to '{{ states.sensor.event_c2be08.attributes["time"] }}' but it won't display anything, not even with '{{state}}'.

Any idea on how I can extract the attribute values?
