### ISSUE TITLE
The card slows down the browser with huge number of requests

### ISSUE THREAD

**Issue by InToSSH** [gadgetchnnel/lovelace-home-feed-card#59]
Hello,
I used this card in my lovelace, but if I add `include_history: true`, it produces a huge number of requests.
After adding the card, I could no longer open the "Edit dashboard", the "Edit" buttons under each card were not loading.
After refresh, the browser (Chrome) said "Waiting for available sockets" and nothing on that dashboard view was loading.
I checked the Developer tools and noticed huge number of requests being made by this card.
These are my settings:
```
type: 'custom:home-feed-card'
title: Home Feed
card_id: main_feed
id_filter: ^home_feed_.*
more_info_on_tap: true
state_color: true
entities:
  - entity: lock.front_door_lock
  - entity: binary_sensor.doods_entry_person_detected
    content_template: Person detected at Front Door
    max_history: 3
    include_history: true
    exclude_states:
      - 'off'
  - entity: binary_sensor.doods_frontyard_person_detected
    content_template: Person detected at Front Yard
    max_history: 3
    include_history: true
    exclude_states:
      - 'off'
  - entity: binary_sensor.entry_door_contact
  - entity: binary_sensor.backyard_door_contact
  - entity: binary_sensor.vestibule_motion
  - entity: input_boolean.home_occupied
```
I noticed this happens only if I have the `include_history: true` set.
With no history it is ok.

HA version: 2020.12.2

![chrome_2021-01-06_02-27-44](https://user-images.githubusercontent.com/6452373/103718434-053e7e80-4fc7-11eb-8e3c-a5346c5ccc2b.png)

**Comment by redpizza69** [comment]
I thought it was only causing a problem if you had 2 entities with "include_history: true", as I have had a home feed card with only 1 entity with "include_history: true" for some time and I hadn't noticed any problems.

Today I added a card with 2 entities with "include_history: true" and my system froze up. The following graph shows cpu for the homeassistant container:
![home feed card](https://user-images.githubusercontent.com/33732374/122416515-b6870e80-cf80-11eb-8ac5-660b4324d90a.png)
The picture above is in 4 sections - ignore section 1, section 2 is with 2 entities with "include_history: true", section 3 with 1 entity with "include_history: true", and section 4 with none.

So my original home feed card was causing problems, but not so much that I noticed. As soon as I added 2 entities with  "include_history: true" then my CPU really went up, and I noticed! For completeness here is my card with 2 x "include_history: true":
```
  - type: 'custom:home-feed-card'
    title: Showers taken today
    max_item_count: 10
    # history_days_back: 1
    # show_empty: false
    more_info_on_tap: true
    state_color: true
    # id_filter: ^home_feed_.*
    entities:
      - entity: binary_sensor.shower_in_use
        format: time
        include_history: true
        remove_repeats: false
        max_history: 10
        content_template: 'Shower'
        exclude_states:
          - "off"
          - "unknown"
      - entity: sensor.hotwater_state
        format: time
        include_history: true
        remove_repeats: false
        max_history: 2
        content_template: 'Hot Water {{state}}'
        exclude_states:
          - "unknown"
 ```
