### ISSUE TITLE
Entities set via services display undefined for triggering entity

### ISSUE THREAD

**Issue by amaximus** [gadgetchnnel/lovelace-home-feed-card#60]
You may reproduce the issue with the following steps:

* create an input_text entity
* create an automation that sets the state of the input_text entity above via its set_value service

```
alias: "test bug"
initial_state: "on"
trigger:
:
action:
  - service: input_text.set_value
    data:
      entity_id: input_text.test_bug
      value: 'test text'
```

* adding this entity to the card displays triggering entity as 'undefined'

Result: triggering entity displayed as undefined (pls see attached screenshot).

Expected behaviour: in such cases either suppress 'undefined@' part or have something like 'hass@' or 'system@' instead.

![feed-card](https://user-images.githubusercontent.com/2511168/104716967-ecea0480-5728-11eb-9da8-1490172e1cc1.png)
