### ISSUE TITLE
Markdown support? 

### ISSUE THREAD

**Issue by pex81** [gadgetchnnel/lovelace-home-feed-card#71]
Hi, I use this card in combination with persistent notification and it works great.
What I can't get to work is the "new line" markdown where in notifications ha, it works.
The bold  works, while the "new line" does not.
Is it possible to solve?
<img width="473" alt="Schermata 2021-06-20 alle 09 24 13" src="https://user-images.githubusercontent.com/58252398/122665743-57581280-d1a9-11eb-9054-7bbbbefb3780.png">
<img width="473" alt="Schermata 2021-06-20 alle 09 24 28" src="https://user-images.githubusercontent.com/58252398/122665746-5de68a00-d1a9-11eb-8fd2-aabc12a256ed.png">

My automation:
```
- alias: "Notifica RAID Synology DSM"
  trigger:
    - platform: state
      entity_id: 
        - sensor.nas_volume_1_status
        - sensor.nas_volume_2_status
      from: 'normal'
      to: 'degrade' 
  action:
    - service: persistent_notification.create
      data:
        title: "RAID Synology"
        message: "Volume 1 **{{ states('sensor.nas_volume_1_status') }}** \n Volume 2 {{ states('sensor.nas_volume_2_status') }}"
        notification_id: synology_raid 
```
My card, I use in combination with custom:button-card
```
      type: custom:home-feed-card
      style: |
        ha-card {
          color: var(--header-text-color);
          box-shadow: none !important;
        }
        state-badge {
          color: var(--button-on-icon-color);
        }                       
        hui-timestamp-display {
          display: none !important;
        }        
      show_empty: false
      show_notification_title: true
```
