### ISSUE TITLE
Request: Suppress initial state

### ISSUE THREAD

**Issue by manonstreet** [gadgetchnnel/lovelace-home-feed-card#8]
New feature request:  The feed shows the initial device state for all monitored entities upon Home Assistant start, regardless if the state has changed.  It would be nice to have an option to suppress these initial states such that only changed states are shown.

**Comment by gadgetchnnel** [comment]
I don't know if it is actually possible for a card to tell if Home Assistant has restarted.
If you are hoping to avoid the issue where an entity is picked up as updated on a restart (due to it going to "unknown" and back to "on) following a restart, you can work around this by using the **include_history** and **remove_repeats** options introduced in the version 0.2.8. Something like this:

```
type: 'custom:home-feed-card'
      title: Home Feed
      show_empty: false
      id_filter: ^home_feed_.*
      entities:
          - entity: binary_sensor.front_door
            include_history: true
            remove_repeats: true
            max_history: 1
```

(You can increase max_history if you want to see multiple changes to the entity)

This will exclude both "unknown" states and those where the current state is the same as the previous one (which happens after filtering the "unknown" states) so, although it won't stop the state from showing in the feed following a restart, it will show the correct updated time.
