### ISSUE TITLE
Avoid updates in card at 00:00

### ISSUE THREAD

**Issue by FragMenthor** [gadgetchnnel/lovelace-home-feed-card#80]
Hello! A really use your card a lot, the only thing that now does not work for me is the fact that the card updates all entitie's state at 00:00:

![image](https://user-images.githubusercontent.com/74264069/132668741-bee42da3-0a5a-422f-8cec-42c83c6beefd.png)

Is it possible to avoid this?

Here is my code:
```
type: custom:home-feed-card
title: Eventos da Casa
card_id: main_feed
show_empty: false
calendars: []
more_info_on_tap: true
state_color: true
compact_mode: false
exact_durations: false
entities:
  - entity: binary_sensor.porta_principal_contact
    format: datetime
    include_history: true
    max_history: 4
    remove_repeats: true
    history_days_back: 2
    exclude_states:
      - unavailable
  - entity: binary_sensor.porta_cave_contact
    format: datetime
    remove_repeats: true
    include_history: true
    max_history: 4
    history_days_back: 2
    exclude_states:
      - unavailable
  - entity: counter.contador_correio
    format: datetime
    include_history: true
    max_history: 2
    history_days_back: 2
    remove_repeats: true
    state_map:
      '0': Sem correio
  - entity: automation.rotina_matinal
    format: datetime
    content_template: Rotina Matinal @ Activada
  - entity: input_select.maquina_loica
    format: datetime
    include_history: true
    max_history: 4
    history_days_back: 2
    remove_repeats: true
  - entity: group.grupo_casa
    format: datetime
    state_map:
      not_home: Ausente
      home: Em casa
    include_history: true
    max_history: 2
    history_days_back: 2
  - entity: input_boolean.modo_refeicao
    format: datetime
    include_history: true
    max_history: 2
    history_days_back: 2
  - entity: input_boolean.modo_dormir
    format: datetime
    include_history: true
    max_history: 2
    history_days_back: 2
  - entity: alarm_control_panel.alarme_geral
    format: datetime
    include_history: true
    max_history: 4
    history_days_back: 2
    remove_repeats: true
```

Thanks again!
