### ISSUE TITLE
History not working

### ISSUE THREAD

**Issue by guy0nabuffalo** [gadgetchnnel/lovelace-home-feed-card#84]
Card is only showing entries for the currect day even though history_days_back is set. Confirmed history/DB is configured correctly in home assistant.
```
type: custom:home-feed-card
compact_mode: true
entities:
  - entity: sensor.bb_last_feeding_from
    name: Last Fed
    format: datetime
    include_history: true
    max_history: 50
    remove_repeats: false
    history_days_back: 10
```
![image](https://user-images.githubusercontent.com/42823584/167702834-68c5a73f-c34c-4fbb-b33a-1984cfb41ccd.png)
