### ISSUE TITLE
History detail not displaying

### ISSUE THREAD

**Issue by nferch** [gadgetchnnel/lovelace-home-feed-card#96]
This card does exactly what I would like it to, but there seems to be some sort of glitch in loading or displaying the history.

Upon an initial load or browser refresh, the card will display timestamps, but not the detail:

![image](https://user-images.githubusercontent.com/1644112/216844916-8d90824f-3fb2-41d3-acc8-93a13250461f.png)

but strangely, if you go to edit the card, it will display correctly, and if you exit the editor, it will be displayed

![image](https://user-images.githubusercontent.com/1644112/216844944-ea802792-ff17-4b23-87e5-c4f2f0585a77.png)

config is pretty simple:

```
type: custom:home-feed-card
title: Apartment Door Activity
max_item_count: 10
entities:
  - entity: input_text.apartment_door_status
    include_history: true
    remove_repeats: false
```

Sorry if I missed anything important, I'm a novice when it comes to Lovelace and frontend dev in general.
